<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="64244" started-at="2021-01-29T19:32:02 IST" finished-at="2021-01-29T19:33:06 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="64244" started-at="2021-01-29T19:32:02 IST" finished-at="2021-01-29T19:33:06 IST">
      <class name="com.hybrid.testcases.GenericUIValidation">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.hybrid.testcases.GenericUIValidation@7748410a]" name="setUp" is-config="true" duration-ms="13924" started-at="2021-01-29T19:32:02 IST" finished-at="2021-01-29T19:32:16 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="a_LoginCrendentials()[pri:0, instance:com.hybrid.testcases.GenericUIValidation@7748410a]" name="a_LoginCrendentials" duration-ms="1520" started-at="2021-01-29T19:32:16 IST" finished-at="2021-01-29T19:32:17 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a_LoginCrendentials -->
        <test-method status="FAIL" signature="b_loginClick()[pri:0, instance:com.hybrid.testcases.GenericUIValidation@7748410a]" name="b_loginClick" duration-ms="3117" started-at="2021-01-29T19:32:17 IST" finished-at="2021-01-29T19:32:20 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Planisware 6 - Home] but found [Planisware Application Server]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Planisware 6 - Home] but found [Planisware Application Server]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.hybrid.testcases.GenericUIValidation.b_loginClick(GenericUIValidation.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- b_loginClick -->
        <test-method status="PASS" signature="d_selectingStartAndEndDate()[pri:0, instance:com.hybrid.testcases.GenericUIValidation@7748410a]" name="d_selectingStartAndEndDate" duration-ms="45548" started-at="2021-01-29T19:32:20 IST" finished-at="2021-01-29T19:33:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- d_selectingStartAndEndDate -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.hybrid.testcases.GenericUIValidation@7748410a]" name="tearDown" duration-ms="1" started-at="2021-01-29T19:33:06 IST" finished-at="2021-01-29T19:33:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.hybrid.testcases.GenericUIValidation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
